version: "3"
services:
  develop:
    build: .
    ports:
      - "4401:4401"
    container_name: gfw-contact-develop
    environment:
      PORT: 4401
      NODE_PATH: app/src
      NODE_ENV: dev
      QUEUE_URL: redis://mymachine:6379
      QUEUE_PROVIDER: redis
      QUEUE_NAME: mail
      REDIS_PORT_6379_TCP_ADDR: redis
      GATEWAY_URL: http://mymachine:9000
      LOCAL_URL: http://mymachine:4401
      WRI_MAIL_RECIPIENTS: <mails>
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: develop
    volumes:
      - ./app:/opt/gfw-contact-api/app
