version: "3"
services:
  test:
    build: .
    ports:
      - "4400"
    container_name: gfw-contact-test
    environment:
      PORT: 4400
      NODE_ENV: test
      GATEWAY_URL: http://mymachine:9000
      QUEUE_NAME: mail
      QUEUE_PROVIDER: redis
      QUEUE_URL: redis://redis:6379
      TARGET_SHEET_ID: TARGET_SHEET_ID
      LOCAL_URL: http://gfw-contact:4400
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      FASTLY_ENABLED: "false"
    command: test
    depends_on:
      - redis

  redis:
    image: redis
    container_name: gfw-contact-api-redis
    ports:
      - "6379"

